branch-defaults:
  main:
    environment: rt-auth-api-prod
global:
  application_name: rt-auth-api
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
